services:
  db:
    image: postgres:15-alpine
    container_name: codify-postgres-dev
    environment:
      POSTGRES_DB: codify_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d codify_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      target: development
    container_name: codify-backend-dev
    ports:
      - "5000:5000"
    env_file:
      - .env.development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

volumes:
  postgres-data:
