version: "3.8"

services:
  neon-local:
    image: ghcr.io/neondatabase/neon-local:latest
    container_name: neon-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - neon-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: codify-backend-dev
    ports:
      - "5000:5000"
    env_file:
      - .env.development
    depends_on:
      neon-local:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

volumes:
  neon-data:
