version: "3.8"

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # You'll need to set these variables in a .env file or through Docker environment variables
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN}
    restart: unless-stopped
